export const ROLES_ADMINISTRATION = [
  "role_bu_site_manager",
  "role_tender_engineer",
  "role_operations_manager",
  "role_project_manager",
  "role_assistant_pm",
  "role_project_engineer",
  "role_site_supervisor",
  "role_administrative_officer",
  "role_cp_niv1_sippt",
  "role_cp_niv1",
  "role_membre_sippt_niv3",
];

export function defaultDossier() {
  return {
    meta: {
      version: 1,
      statut: "brouillon",
      dateDerniereModif: new Date().toISOString().slice(0, 10),
    },
    identification: {
      numeroChantier: "",
      nomChantier: "",
    },
    renseignementsGeneraux: {
      client: "",
      maitreOeuvre: "",
      maitreOuvrage: "",
      nomRespPaiements: "",
      nomRespTravaux: "",
      nomConseillerPrevention: "",
      adresseChantier: "",
      adresseFacturation: "",
      numeroTva: "",
      tauxTva: "",
      nbExemplairesFacture: "",
      etatAvancements: "",
      declarationCreance: "",
      declarationOnss: "",
      formuleRevision: "",
      bureauArchitecture: "",
      beTechSpeciales: "",
      coordinateurSecurite: "",
    },
    administration: {
      responsables: Object.fromEntries(ROLES_ADMINISTRATION.map((r) => [r, ""])),
      revisionsPPSS: [],
      descriptionTravaux: "",
      dateCommande: "",
      dateTransfert: "",
      dateDebutTravaux: "",
      dateFinTravaux: "",
      declarationTravauxOnss: false,
      accuseReception: false,
      declarationTravauxCnac: false,
      cautionnement: "",
      dureeGarantie: "",
      dateReceptionProvisoire: "",
      dateReceptionDefinitive: "",
      dossierAsBuilt: "",
      dateRemise: "",
      entretienAPrevoir: false,
      frequence: "",
      reunionChantier: false,
      jourFrequence: "",
      etatDesLieux: false,
      formationClient: false,
      toutRisqueChantier: false,
    },
    sousTraitants: [],
    caracteristiques: {
      planEnAnnexe: false,
      particularitesAcces: "",
      autresPointRassemblement: "",
      refectoire: false,
      wc: false,
      stockage: false,
      evacuationDechets: false,
      nettoyageInstallationsSanitaires: false,
      eclairage: false,
      zoneCirculation: "",
      zoneTravail: "",
      electriciteAlimTerre: false,
      eau: false,
      panneauSignalisation: false,
      barrieres: false,
      autorisationsParticulieres: "",
      materielSpecifique: "",
      gardeCorps: false,
      ligneDeVie: false,
      filetRetention: false,
      produitsDangereux: "",
      presenceSecouristes: false,
      permisFeu: false,
      permisTravail: false,
    },
    caracterisation: {
      mode: "complet",
      corpsMetier: [],
      aide: { heures: false, hauteur: false, ht: false, confine: false },
    },
    analyseRisques: {
      activitesCochees: [],
      itemsCochesAbrege: [],
    },
    reglesSpecifiques: {
      conseillerPrevention: "",
      serviceIncendie: "",
      serviceIncendieInterne: "",
      hopitalPlusProcheIds: [],
      codePostalChantier: "",
      infirmerieClient: "",
    },
    derogationsPSS: { neant: true, items: [] },
    questionsCoordination: [],
    accordsObligations: { accueilEnLigne: "", lienVideo: "", lienQuestionnaire: "" },
    planParticulier: { notes: "", enginsSpeciaux: [] },
    annexe4: { accepte: false },
  };
}
